kitty 0.41.0 (26747284bb) created by Kovid Goyal
Linux IdeaPad-3-15IAU7 6.11.0-21-generic #21~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Feb 24 16:52:15 UTC 2 x86_64
Ubuntu 24.04.2 LTS IdeaPad-3-15IAU7 /dev/tty

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.2 LTS"
Running under: Wayland (GNOME Shell 46.0) missing: blur server_side_decorations cursor_shape layer_shell icon
OpenGL: '4.6 (Core Profile) Mesa 24.2.8-1ubuntu1~24.04.1' Detected version: 4.6
Frozen: True
Fonts:
  medium: DejaVuSansMono: /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf:0
          Features: ()
    bold: DejaVuSansMono-Bold: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf:0
          Features: ()
  italic: DejaVuSansMono-Oblique: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Oblique.ttf:0
          Features: ()
      bi: DejaVuSansMono-BoldOblique: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-BoldOblique.ttf:0
          Features: ()
Paths:
  kitty: /home/amulgaurav/.local/kitty.app/bin/kitty
  base dir: /home/amulgaurav/.local/kitty.app/lib/kitty
  extensions dir: /home/amulgaurav/.local/kitty.app/lib/kitty-extensions
  system shell: /usr/bin/zsh
System color scheme: dark. Applied color theme type: none
Loaded config files:
  /home/amulgaurav/.config/kitty/kitty.conf

Config options different from defaults:
background_image        /home/amulgaurav/Pictures/wallpapers/a_person_standing_on_a_broken_object_in_a_field_with_a_large_white_moon.png
background_image_layout cscaled
background_tint         0.8
enabled_layouts         ['tall', 'fat', 'grid', 'horizontal', 'splits', 'stack', 'vertical']
font_family             family='DejaVu Sans Mono' postscript_name=DejaVuSansMono
tab_bar_style           powerline
url_style               1
Added shortcuts:
	ctrl+alt+enter →  launch --cwd=current
Colors:
	background              #0d0f31   
	color1                  #ff16b0   
	color10                 #b3f361   
	color11                 #ffea16   
	color12                 #46bdff   
	color13                 #f806fa   
	color14                 #6be4e6   
	color15                 #feffff   
	color2                  #b3f361   
	color3                  #ffea16   
	color4                  #46bdff   
	color5                  #f806fa   
	color6                  #59e1e3   
	color7                  #feffff   
	color8                  #000000   
	color9                  #ff16b0   
	cursor                  #59e1e3   
	foreground              #ffffff   
	selection_background    #00d5eb   
	url_color               #f806fa   

Important environment variables seen by the kitty process:
	PATH                                /home/amulgaurav/.local/kitty.app/bin:/home/amulgaurav/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
	LANG                                en_US.UTF-8
	SHELL                               /usr/bin/zsh
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                amulgaurav
	XDG_DATA_DIRS                       /home/amulgaurav/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 ubuntu:GNOME
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 ubuntu
	XDG_SESSION_TYPE                    wayland
